### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by sakne** [roydejong/timbot#15]
Timbot is starting.
Connecting to Discord...
[Discord] Logging in...
[Sellout] Sellout list initialized from remote, 946 items
[Discord] Bot is ready; logged in as Xesh Bot#7579.
[Discord]  -->  Member of server SAKNΞ's server, target channel is #stream-announcements
[Discord] Discovered 1 channels to announce to for stream-announcements.
[StreamActivity] Cleared current activity.
[TwitchMonitor] Configured stream status polling for channels: <some_twitch_channel_name>, <some_twitch_channel_name> (60000ms interval)
[Twitch]  ▪ ▪ ▪ ▪ ▪  Refreshing now (Initial refresh after start-up)  ▪ ▪ ▪ ▪ ▪ 
[TwitchApi] API request failed with Helix error: Invalid login names, emails or IDs in request (Bad Request/400)
[TwitchMonitor] Error in users refresh: Error: Request failed with status code 400

    at createError (C:\Users\SAKNE\Desktop\bots\Xesh Bot\timbot\timbot\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\SAKNE\Desktop\bots\Xesh Bot\timbot\timbot\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\SAKNE\Desktop\bots\Xesh Bot\timbot\timbot\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by roydejong** [comment]
The important part is in the error from the Twitch API (Helix):

```
Invalid login names, emails or IDs in request
```

Most likely there is an invalid character in the stream names you're monitoring. If you share your config we can take a look, but in general: make sure you're using the channel names as they appear in the twitch.tv URL.
