### ISSUE TITLE
Hey i have a little Bug

### ISSUE THREAD

**Issue by MrWhiteFlamesYT** [roydejong/timbot#26]
Hey there

When i have the bot running and all when it does its "[Twitch]  ▪ ▪ ▪ ▪ ▪  Refreshing now (Periodic refresh)  ▪ ▪ ▪ ▪ ▪" and gets a live notification from a streamer i listed, then it gives me this error when it tries to send the message in the channel. and yes the bot it is connecting too has all the perms on the channel. can you help me fix this please?

[TwitchMonitor] Stream channel has gone online: mrwhiteflamesyt_dev
[StreamActivity] Update current activity: watching mrwhiteflamesyt_dev.
[TwitchMonitor] Error in streams refresh: TypeError: fields.flat is not a function
    at Function.normalizeFields (/Whitebots/Stream-Notify/timbot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/Whitebots/Stream-Notify/timbot/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/Whitebots/Stream-Notify/timbot/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at Function.createForStream (/Whitebots/Stream-Notify/timbot/live-embed.js:29:16)
    at TwitchMonitor.onChannelLiveUpdate (/Whitebots/Stream-Notify/timbot/index.js:492:32)
    at Function.handleChannelLiveUpdate (/Whitebots/Stream-Notify/timbot/twitch-monitor.js:220:21)
    at Function.handleStreamList (/Whitebots/Stream-Notify/timbot/twitch-monitor.js:182:23)
    at TwitchApi.fetchStreams.then (/Whitebots/Stream-Notify/timbot/twitch-monitor.js:95:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by roydejong** [comment]
This most likely means you are using an older version of Node.js, try updating to v12.

See: https://stackoverflow.com/a/61034427/1410310

**Comment by MrWhiteFlamesYT** [comment]
How can i get a specific role to be pinged and does it use role id or name?

**Comment by roydejong** [comment]
> How can i get a specific role to be pinged and does it use role id or name?

For basic config check out the README. You can define specific roles under the `discord_mentions` config option.

You have to set these by name currently, setting it by ID is an open request: #24
