### ISSUE TITLE
I have a little BUG!

### ISSUE THREAD

**Issue by MrWhiteFlamesYT** [roydejong/timbot#27]
Hello There

I am having some errors show up when the bot needs to send message to the channel, can you also change it so that the channel id is used rather than the channel name, but the error that follows is what it give me when it detects the streamer go live on twitch! The bot does have all permissions for the channel it is suppose to send it.

[StreamActivity] Update current activity: watching mrwhiteflamesyt_dev.
[TwitchMonitor] Error in streams refresh: TypeError: fields.flat is not a function
    at Function.normalizeFields (/Whitebots/Stream-Notify/timbot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/Whitebots/Stream-Notify/timbot/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/Whitebots/Stream-Notify/timbot/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at Function.createForStream (/Whitebots/Stream-Notify/timbot/live-embed.js:29:16)
    at TwitchMonitor.onChannelLiveUpdate (/Whitebots/Stream-Notify/timbot/index.js:492:32)
    at Function.handleChannelLiveUpdate (/Whitebots/Stream-Notify/timbot/twitch-monitor.js:220:21)
    at Function.handleStreamList (/Whitebots/Stream-Notify/timbot/twitch-monitor.js:182:23)
    at TwitchApi.fetchStreams.then (/Whitebots/Stream-Notify/timbot/twitch-monitor.js:95:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    
    Can you help me? because i think previous one got removed or never created, never got notification why it was closed if it got closed.
    
    thank you MrWhiteFlamesYT

**Comment by MrWhiteFlamesYT** [comment]
Didn't get the notification of previous issue
