### ISSUE TITLE
I have this problem when im going to start the bot

### ISSUE THREAD

**Issue by scuffitotw** [roydejong/timbot#33]
This is the error code:

internal/modules/cjs/loader.js:1131
    throw err;
    ^

SyntaxError: /root/timbot-master/config.json: Unexpected token } in JSON at position 138
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/root/timbot-master/brugadirectos.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)

**Comment by roydejong** [comment]
Hey, it looks like you may have made a typo in your config file, which means it cannot be read.

It's impossible to say what the problem is without seeing your config file (it contains secrets, so please don't show it).

Make sure your string values are properly wrapped in double quotes, and that there are no commas or anything missing.
